### ISSUE TITLE
warning in submodules hosted outside of the organization

### ISSUE THREAD

**Issue by wildsm** [bandframework/bandframework#112]
When I do a fresh recursive clone, I receive the warning

`
warning: redirecting to https://github.com/asemposki/SAMBA.git/
`

It looks like one needs to add `.git` to submodules hosted outside of the bandframework organization

**Comment by wildsm** [comment]
Attempting to address in #111

**Comment by asemposki** [comment]
I'll check the PR to fix this tonight.

**Comment by asemposki** [comment]
This worked, so I'm closing the issue.
