### ISSUE TITLE
Ensure SDK list is updated prior to release v0.4

### ISSUE THREAD

**Issue by mosesyhc** [bandframework/bandframework#113]
The list of [SDK policies](https://github.com/bandframework/bandframework/tree/main/resources/sdkpolicies) should match all software included in BAND, prior to next release.

**Comment by wildsm** [comment]
I believe this should be done before v0.4, but is more general; it should be added to https://github.com/bandframework/bandframework/blob/main/resources/dev_guide/release-proc.rst

**Comment by wildsm** [comment]
This was fixed by #116.

Will ensure that the Pull Request for v0.4 uses the release process in develop (https://github.com/bandframework/bandframework/blob/develop/resources/dev_guide/release-proc.rst)
