### ISSUE TITLE
Define the role of the examples directory

### ISSUE THREAD

**Issue by furnstahl** [bandframework/bandframework#114]
At present bandframework/examples contains only a README.md file, while the pointer to "examples" in the top level README.md is to bandframework/software. Figure out what to do with examples!

**Comment by asemposki** [comment]
Our eventual EOS repo from our paper would go under Examples, if Examples means a direct use of BAND tools in a paper. However, that is post v0.4 right now.

**Comment by furnstahl** [comment]
A separation could be that "examples" in software would be code/scripts/etc. to get you started. In bandframework/examples we would put notebooks etc. that generate results for papers and _also_ enable pointers to papers/people who have used the tools but did not provide code to us.

**Comment by DanielRPhillips** [comment]
I had originally envisioned the Examples directory in our repo in the way @asemposki describes it. This would be consistent with @furnstahl's "pointers to papers/people who have used the tools but did not provide code to us."

The way I say it the "Examples" in our software directory (e.g. BRICK, BFRESCOX) should be examples of principled Bayesian UQ that are:
- Specific to a particular problem
- Contain software that others may wish to adopt for their own use

It may be that QGP_Bayes belongs in bandframework/examples.

**Comment by wildsm** [comment]
Based on the above, the changes to the README staged for v0.4.0 should probably be changed (see the diffs at https://github.com/bandframework/bandframework/pull/131/files). It would be great if someone could provide a pull request to `develop` with a suggested change.

**Comment by wildsm** [comment]
Following up on this thread, what do people think of the README:

https://github.com/bandframework/bandframework/pull/131/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

**Comment by DanielRPhillips** [comment]
I am planning to work on the README, but I do not have time to do it until Saturday.

**Comment by wildsm** [comment]
> Based on the above, the changes to the README staged for v0.4.0 should probably be changed (see the diffs at https://github.com/bandframework/bandframework/pull/131/files). It would be great if someone could provide a pull request to `develop` with a suggested change.

Great, I suggest making your changes to the `v04/documentation` branch (see #138).

**Comment by DanielRPhillips** [comment]
README file has been updated to reflect my understanding of what we decided in this conversation.
