### ISSUE TITLE
Populate and add admin mailing list throughout

### ISSUE THREAD

**Issue by wildsm** [bandframework/bandframework#22]
Proposed code of conduct references the new contact address
 bandframework@cels.anl.gov

If there is not a better address, current individuals should be subscribed to this list and the address should potentially be added elsewhere/throughout the repo. 

Consider stating recipients of the above email?

**Comment by DanielRPhillips** [comment]
It's great you got us an email address. I think there needs to be one individual who's responsible for receiving email from that address--or at least for allocating the task of responding if they don't respond themself. 

I like the idea of it going to several people, but in that case isn't there a risk that no-one responds because everyone thinks someone else is going to?

**Comment by wildsm** [comment]
All good for an individual or multiple. 

For such email addresses with multiple subscribers, the convention is the responses are replied all. This way the recipient sees the individual who sent the response and the other subscribers (and the list archive) are all aware.

**Comment by DanielRPhillips** [comment]
Sounds good. In that case, yes, we should state the recipients of that email. An initial list would be the PIs at each institution: 
Daniel Phillips
Dick Furnstahl
Stefan Wild
Frederi Viens
Should the list be broader? I can think of people who could be usefully added, but I would think we do not want every BAND member to receive it. 

For CoC violations what is the complainant supposed to do if they are complaining about one of the individuals that is subscribed to this email list?

**Comment by wildsm** [comment]
CoC has now been updated to reflect the above, pull request submitted:

The current recipients of this email are Daniel Phillips, Dick Furnstahl,
Stefan Wild, and Frederi Viens. To report a concern about one of these 
please, email the others. 

Will close this issue once have received confirmation from others list is working as intended.

**Comment by wildsm** [comment]
Test confirmed.
