### ISSUE TITLE
Add website (and others?) dependencies to release process

### ISSUE THREAD

**Issue by wildsm** [bandframework/bandframework#24]
The [release process](https://github.com/bandframework/bandframework/blob/develop/release-proc.rst) currently does not indicate what other items need to updated. 

For BANDFramework, the [website's repo](https://github.com/bandframework/bandframework.github.io) probably should be updated as part of the release process.

Additionally, if there are communities who should be alerted to the latest release (contributors on github? user/stakeholder mailing list(s)? people who starred the repo? ...), consider specifying these in the release process.

**Comment by wildsm** [comment]
Related to [Issue 16][(url](https://github.com/bandframework/bandframework/issues/16))

**Comment by MattPlumlee** [comment]
I support tabling this issue until we can enable actions for the repo.  Likely next version.

**Comment by wildsm** [comment]
This will be addressed in v0.3 via the changes in the release process
https://github.com/bandframework/bandframework/blob/develop/resources/dev_guide/release-proc.rst

**Comment by wildsm** [comment]
Closed with #93
