### ISSUE TITLE
AUTHORS missing and/or incomplete

### ISSUE THREAD

**Issue by wildsm** [bandframework/bandframework#26]
The [CONTRIBUTING.rst](https://github.com/bandframework/bandframework/blob/develop/CONTRIBUTING.rst) file references [AUTHORS](https://github.com/bandframework/bandframework/blob/develop/AUTHORS), which currently does not exist.

Before a release:
- It should be populated with an initial set of authors, or 
- The reference should be removed (see also [release-proc.rst](https://github.com/bandframework/bandframework/blob/develop/release-proc.rst) )

**Comment by DanielRPhillips** [comment]
If the issue tagged by @ozgesurer above is resolved, then this one can be too
