### ISSUE TITLE
Unable to enable Actions for this repository. 

### ISSUE THREAD

**Issue by wildsm** [bandframework/bandframework#32]
I have never seen this before:
Obtain"Unable to enable Actions for this repository." when trying to enable actions from main Actions page on the repo.

**Comment by ozgesurer** [comment]
[here](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository) it explains a bit. However, my authorization level does not allow me to reach out settings section of bandframework I guess. Once I am allowed, I can play with it a bit.

**Comment by MattPlumlee** [comment]
I see "Allow all actions and reusable workflows" checked under our settings.  Am I looking in the wrong place?

**Comment by ozgesurer** [comment]
Although it is checked, if you go Actions tab and click on green button saying Enable actions, it won't.

**Comment by MattPlumlee** [comment]
Thanks, this helps.  I have no idea.  They work for other repos in this org. It seems like a bug.  Is there any github support for the free version we are on?

**Comment by furnstahl** [comment]
For the record, I checked the other organizations I own and don't see this on any repos. I don't see any obvious fixes that apply here from past reports (e.g., in github community https://github.community/); I don't see recent reports.

**Comment by MattPlumlee** [comment]
My advised solution is not a fun one, but maybe isn't that bad.  After `v0.2` release, we should (1) rename this repo, (2) clone this repo into a new one named `bandframework`, and (3a) if we can create actions, then leave the new repo or (3b) if we cannot create actions, delete the new `bandframework` and instead create a new `bandframework` with same files, but no clone.  Given our experiences with other repo, I think (3a) or (3b) will work, but might be a bit painful.

**Comment by DanielRPhillips** [comment]
@MattPlumlee: can we attempt (3a) or (3b) before v0.2? It would be good to be able to track downloads as soon as v0.2 is released.

**Comment by MattPlumlee** [comment]
@DanielRPhillips See slack convo for timing.

**Comment by wildsm** [comment]
I have opened up a ticket with github support to give one last go (link viewable by me: https://support.github.com/ticket/personal/0/1804893)

**Comment by wildsm** [comment]
> My advised solution is not a fun one, but maybe isn't that bad. After `v0.2` release, we should (1) rename this repo, (2) clone this repo into a new one named `bandframework`, and (3a) if we can create actions, then leave the new repo or (3b) if we cannot create actions, delete the new `bandframework` and instead create a new `bandframework` with same files, but no clone. Given our experiences with other repo, I think (3a) or (3b) will work, but might be a bit painful.

Unfortunately, we do not yet have a successful case of being able to enable actions on new repos in this organization. @furnstahl and I each made new public repos in the org and experienced the same error (unable to enable actions). 

@MattPlumlee - see if you can succeed (new public repo in this org, then enable actions)

**Comment by MattPlumlee** [comment]
Confirmed that I get the message:
> Unable to enable Actions for this repository. 

on a test repository.

**Comment by wildsm** [comment]
So we are stuck. I suggest people with paid github accounts open a ticket with github, maybe we will get a response/fix.

This is obviously related to (and holding up):
https://github.com/bandframework/bandframework/issues/18
https://github.com/bandframework/bandframework/issues/20

**Comment by wildsm** [comment]
Confirmed that actions can now been enabled in other repos in the org.
