### ISSUE TITLE
All modules should have updated SDK.

### ISSUE THREAD

**Issue by MattPlumlee** [bandframework/bandframework#36]
Before release, all modules should have updated SDK.  This can only happen once it is approved and merged in (pull request #33 )

**Comment by asemposki** [comment]
Can any of us merge the PR or are we waiting on Stefan and Ozge to approve still?

**Comment by wildsm** [comment]
(responding to @asemposki): @MattPlumlee to update the code and then we can merge

**Comment by wildsm** [comment]
@asemposki @odell @ozgesurer @danOSU - 
Here is what the new SDK will look like: https://github.com/bandframework/bandframework/pull/33/files
You should see from the highlighted differences that it should be very simple for you to update from 0.1 to 0.2
Please go ahead and do so now and drop a note here when done... hoping for a BAND release on Friday!

**Comment by wildsm** [comment]
@danOSU is done: https://github.com/bandframework/bandframework/pull/42

**Comment by wildsm** [comment]
frescox done: https://github.com/bandframework/bandframework/pull/44

**Comment by asemposki** [comment]
I have updated the SDK and opened a PR for my submodule update.

**Comment by wildsm** [comment]
@odell done: https://github.com/bandframework/bandframework/pull/48

Thanks all! Closing this issue
