### ISSUE TITLE
update documentation for submodule installation

### ISSUE THREAD

**Issue by danOSU** [bandframework/bandframework#54]
`git clone <repo url> ` will not download the submodules. 
Instead use `git clone --recursive <repo url>` to clone the repo with all the submodules. The readme needs to be updated with this information.

**Comment by wildsm** [comment]
Great issue @danOSU
The above would do it for an initial clone, but I'm hoping you might be able to help test something for me if you just do a normal git clone (and find that your environment has not pulled in submodules).

Clone bandframework
Check that software/SAMBA (for example) is empty
Do `git submodule update --init --recursive `
Check that the directories in software/ are now nonempty

**Comment by danOSU** [comment]
yes. `git submodule update --init` seems to initialize and get all the submodule contents. I think the recursive flag is needed if there are submodules within the submodules.

If someone wants to just use one of the submodules and not clone the rest they can do it in two steps.

`git submodule init <submodule name>`
`git submodule update `

**Comment by wildsm** [comment]
@danOSU - thanks for helping diagnose. What do you think about adding something like the following to the README?

## Submodules

BAND Framework currently includes some dependencies via git submodules. Currently, the following submodules are employed:

* [software/](software/)QGP_Bayes
* [software/](software/)SAMBA 
* [software/](software/)surmise

As a consequence, when cloning the BAND Framework repository, the submodules can be retrieved automatically via
- `git clone --recursive` (in place of the usual `git clone`)

If you have already cloned the repository, the following modified `git` commands can be used:
- `git submodule update --init --recursive` (to obtain all submodules and any submodules those submodules have)
- `git pull --recurse-submodules=yes` (in place of the usual `git pull`)
- `git submodule update --init` (additionally, after `git pull`)
- `git submodule update --init software/surmise`
  (variant of the previous item, in case you want to only get the surmise submodule)

**Comment by danOSU** [comment]
Looks good @wildsm. This is all anyone would need to get the submodules when they clone. I would also add an instruction to check the git version >= 2.38.0 because these commands might not be available in older versions.

**Comment by wildsm** [comment]
Addressed with #61 

Thanks @danOSU & @mosesyhc
